TaskManagement/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using TaskManagement.Data;
using TaskManagement.Models;


namespace TaskManagement.Controllers
{
    public class RoleController : Controller
    {
        private readonly TaskManagementContext _context;

        public RoleController(TaskManagementContext context)
        {
            _context = context;
        }

        // GET: Role
        public IActionResult Index()
        {
            var roles = _context.Role.ToList();
            return View(roles);
        }

        // GET: Role/Details/5
        public IActionResult Details(int id)
        {
            var role = _context.Role.Find(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // GET: Role/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Role/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("RoleID,RoleName,Active,CreatedAt,UpdatedAt,CreatedBy,UpdatedBy")] Role role)
        {
            if (ModelState.IsValid)
            {
                role.CreatedAt = DateTime.Now;
                _context.Add(role);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Role/Edit/5
        public IActionResult Edit(int id)
        {
            var role = _context.Role.Find(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Role/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("RoleID,RoleName,Active,CreatedAt,UpdatedAt,CreatedBy,UpdatedBy")] Role role)
        {
            if (id != role.RoleID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    role.UpdatedAt = DateTime.Now;
                    _context.Update(role);
                    _context.SaveChanges();
                }
                catch (Exception)
                {
                    if (!RoleExists(role.RoleID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Role/Delete/5
        public IActionResult Delete(int id)
        {
            var role = _context.Role.Find(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Role/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var role = _context.Role.Find(id);
            _context.Role.Remove(role);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Role.Any(e => e.RoleID == id);
        }
    }
}

TaskManagement/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using TaskManagement.Data;
using TaskManagement.Models;
using Task = TaskManagement.Models.Task;

namespace TaskManagement.Controllers
{
    public class TaskController : Controller
    {
        private readonly TaskManagementContext _context;

        public TaskController(TaskManagementContext context)
        {
            _context = context;
        }

        // GET: Task
        public IActionResult Index()
        {
            var tasks = _context.Task.Include(x => x.Project).ToList();
            return View(tasks);
        }

        // GET: Task/Details/5
        public IActionResult Details(int id)
        {
            var task = _context.Task.Find(id);
            if (task == null)
            {
                return NotFound();
            }
            return View(task);
        }

        // GET: Task/Create
        public IActionResult Create()
        {
            var task = new TaskManagement.Models.Task();

            var taskStatusOption = _context.CodeTable.Where(x => x.CodeTableType == "TaskStatus").ToList();
            taskStatusOption.Insert(0, new CodeTable { Value = "", Name = "-- Select Status --" });
            ViewBag.Status = new SelectList(taskStatusOption, "Value", "Name", task.Status);

            var priorityOption = _context.CodeTable.Where(x => x.CodeTableType == "Priority").ToList();
            priorityOption.Insert(0, new CodeTable { Value = "", Name = "-- Select Status --" });
            ViewBag.Priority = new SelectList(priorityOption, "Value", "Name", task.Priority);

            var projectOption = _context.Project.Where(x => x.Status == "Draft" || x.Status == "Rejected").Select(x => new
            {
                x.ProjectID,
                ProjectName = String.Concat(x.ProjectID, " - ", x.ProjectName)
            })
            .ToList();

            projectOption.Insert(0, new { ProjectID = 0, ProjectName = "-- Select Project --" });
            ViewBag.Projects = new SelectList(projectOption, "ProjectID", "ProjectName", task.Status);
            return View();

            //var departmentOption = _context.CodeTable.Where(x => x.CodeTableType == "Department").ToList();
            //departmentOption.Insert(0, new CodeTable { Value = "", Name = "-- Select Department --" });
            //ViewBag.Department = new SelectList(departmentOption, "Value", "Name");


        }

        // POST: Task/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("TaskID,TaskName,Description,ProjectID,AssignedTo,Status,Priority,Department,DueDate,Active,CreatedAt,UpdatedAt,CreatedBy,UpdatedBy")] Task task)
        {
            if (ModelState.IsValid)
            {
                task.CreatedAt = DateTime.Now;
                task.Active = true;
                _context.Add(task);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(task);
        }

        // GET: Task/Edit/5
        public IActionResult Edit(int id)
        {
            var task = _context.Task.Find(id);
            if (task == null)
            {
                return NotFound();
            }
            var taskStatusOption = _context.CodeTable.Where(x => x.CodeTableType == "TaskStatus").ToList();
            taskStatusOption.Insert(0, new CodeTable { Value = "", Name = "-- Select Status --" });
            ViewBag.Status = new SelectList(taskStatusOption, "Value", "Name", task.Status);

            var priorityOption = _context.CodeTable.Where(x => x.CodeTableType == "Priority").ToList();
            priorityOption.Insert(0, new CodeTable { Value = "", Name = "-- Select Status --" });
            ViewBag.Priority = new SelectList(priorityOption, "Value", "Name", task.Priority);

            var projectOption = _context.Project.ToList();
            projectOption.Insert(0, new Project { ProjectID = 0, ProjectName = "-- Select Project --" });
            ViewBag.Projects = new SelectList(projectOption, "ProjectID", "ProjectName", task.Status);
            return View(task);

            //var departmentOption = _context.CodeTable.Where(x => x.CodeTableType == "Department").ToList();
            //departmentOption.Insert(0, new CodeTable { Value = "", Name = "-- Select Department --" });
            //ViewBag.Department = new SelectList(departmentOption, "Value", "Name", task.Department);
        }

        // POST: Task/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("TaskID,TaskName,Description,ProjectID,AssignedTo,Status,Priority,DueDate,Active,CreatedAt,UpdatedAt,CreatedBy,UpdatedBy")] Task task)
        {
            if (id != task.TaskID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    task.UpdatedAt = DateTime.Now;
                    _context.Update(task);
                    _context.SaveChanges();
                }
                catch (Exception)
                {
                    if (!TaskExists(task.TaskID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(task);
        }

        // GET: Task/Delete/5
        public IActionResult Delete(int id)
        {
            var task = _context.Task.Find(id);
            if (task == null)
            {
                return NotFound();
            }
            return View(task);
        }

        // POST: Task/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var task = _context.Task.Find(id);
            _context.Task.Remove(task);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskExists(int id)
        {
            return _context.Task.Any(e => e.TaskID == id);
        }

        [HttpPost("LoadData")]
        public async Task<IActionResult> LoadData()
        {
            var orderCriteria = "TaskID";
            var orderAscendingDirection = true;

            var data = _context.Task.Include(t => t.Project).AsQueryable();

            var totalResultsCount = data.Count();


            var resultData = new { recordsFilter = totalResultsCount, recordTotal = totalResultsCount, data = data };

            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(resultData),
                ContentType = "application/json",
            };

            return result;
        }

        public async Task<IActionResult> CreateOrEdit(int id = 0, int projectID = 0)
        {
            var taskModel = new TaskManagement.Models.Task();

            var taskStatusOption = _context.CodeTable.Where(x => x.CodeTableType == "TaskStatus").ToList();
            taskStatusOption.Insert(0, new CodeTable { Value = "", Name = "-- Select Status --" });
            ViewBag.Status = new SelectList(taskStatusOption, "Value", "Name", taskModel.Status);

            var priorityOption = _context.CodeTable.Where(x => x.CodeTableType == "Priority").ToList();
            priorityOption.Insert(0, new CodeTable { Value = "", Name = "-- Select Status --" });
            ViewBag.Priority = new SelectList(priorityOption, "Value", "Name", taskModel.Priority);

            var projectOption = _context.Project.Where(x => x.Status == "Draft" || x.Status == "Rejected").Select(x => new
            {
                x.ProjectID,
                ProjectName = String.Concat(x.ProjectID, " - ", x.ProjectName)
            })
            .ToList();

            projectOption.Insert(0, new { ProjectID = 0, ProjectName = "-- Select Project --" });
            ViewBag.Projects = new SelectList(projectOption, "ProjectID", "ProjectName", taskModel.Status);

            if (id == 0)
            {

                var task = new TaskManagement.Models.Task();
                task.ProjectID = projectID;
                return View(task);
            }
            else
            {
                var task = await _context.Task.FindAsync(id);
                if (task == null)
                    return NotFound();

                return View(task);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(Task task)
        {
            if (ModelState.IsValid)
            {
                var userName = HttpContext.Session.GetString("UserName");

                if (task.TaskID == 0)
                {
                    //task.CreatedBy = userName;
                    //task.CreatedAt = DateTime.Now;    
                    _context.Add(task);
                }
                else
                {
                    task.UpdatedBy = userName;
                    task.UpdatedAt = DateTime.Now;
                    _context.Update(task);
                }

                await _context.SaveChangesAsync();

            }

            return RedirectToAction("Details", "Project", new { id = task.ProjectID }); // Redirect to the project list
            //return View(task);
        }
    }
}

TaskManagement/Views/Shared/_Layout.cshtml
@{
    bool isLogin = Context.Session.GetString("UserName") == null ? false : true;
    var userName = Context.Session.GetString("UserName");
    var roleName = Context.Session.GetString("RoleName");

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    @*     <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css"> *@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Project</a>
                        </li>
                        @*                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Task</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TaskAssignment" asp-action="Index">Task Assignment</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TaskHistory" asp-action="Index">Task History</a>
                        </li>*@
                   @*     @if (roleName == "Staff" || roleName == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                        }
*@
                        @if (roleName == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                            </li>
                        }
                    </ul>
                </div>
                <div class="sidebar-footer">
                    @if (isLogin)
                    {
                        <span class="navbar-text me-3">Welcome, @userName</span>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="LogOut">Logout</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                    }
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
       @* <div class="container">
            &copy; 2024 - TaskManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @*     <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script> *@
    @*     <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"></script> *@

    <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskManagement/Views/Shared/_LayoutLogin.cshtml
@{
    bool isLogin = Context.Session.GetString("UserName") == null ? false : true;
    var userName = Context.Session.GetString("UserName");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />      
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div class="container">
            &copy; 2024 - TaskManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>